menu:
  title: "&bМеню бафовара" # Название менюшки
  size: 54 # Не меняй если не хочешь проблем

potion:
  cost-per-potion: 5000.0 # Цена за стаканье
  amount: 7  # Количество зелий для стака
  slots:
    # Слоты для зелий
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16

messages:
  nomoney: "&9&lБафовар &7» &cУ вас недостаточно средств!"
  success: "&9&lБафовар &7» &aЗелья успешно стакнуты! Приходи еще."
  reload: "&9&lБафовар &7» &aПлагин AnPotions перезагружен!"
  nobaff:
    - "&9&lБафовар &7» &cУ вас нехватает зелий!"
    - "&9&lБафовар &7» &bПожалуйста, добавьте больше зелий в слоты!"

item:
  material: "BOOK"
  displayName: "&8Псс..."
  customModelData: 1
  slot: 4
  lore:
    - "&7Я могу стакать тебе бафы"
    - "&7Всего за &b5000$ &7за &b7 &7зелий"
    - ""
    - "&7Положи зелья сверху,"
    - "&7и нажми на меня 1 раз"
    - ""
    - "&7Говорят, что это читерно"
    - "&7Если что ты меня не видел"

panels:
  lightGray:
    material: "BLACK_STAINED_GLASS_PANE"
    display_name: " "
    slots:
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34

  gray:
    material: "BLACK_STAINED_GLASS_PANE"
    display_name: " "
    slots:
      - 0
      - 1
      - 2
      - 3
      - 5
      - 6
      - 7
      - 8
      - 9
      - 18
      - 27
      - 36
      - 45
      - 17
      - 26
      - 35
      - 44
      - 53
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43

barriers: #слоты для барьеров
  - 47
  - 46
  - 48
  - 49
  - 50
  - 51
  - 52

barrier123: #Барьер который в данной конфигурайии находиться на 49 слоте, те на месте где должны появляться зелья посли их стаканья.
  material: "BARRIER"
  displayName: "&fБарьер"
  lore:
    - "" # or пробел, если хочешь чтобы было пусто.
  slot: 49

# Пример для кастомных предметов
# customItems: это основа
# custom_item_1: - любое название, НО не должно быть повтора!
# customItems:
#  custom_item_1:
#    material: DIAMOND
#    displayName: '&b123'
#    lore:           #кол-во строк 1>=
#      - '&7123'
#    slots:          #один слот или более.
#      - 1
#      - 2           #СЛОТЫ НЕ ДОЛЖНЫ ПОВТОРЯТЬСЯ, те если ставишь убери слот сверху.
#      - 3